### ISSUE TITLE
Test google-map-poly element

### ISSUE THREAD

**Issue by KK578** [KK578/comp3001#1]
GoogleWebComponents/google-map appears to provide a nice way to easily draw a connected line using a set of points.

If the data from the backend just consists of lat/long pairs, we can easily create a list of this in the app to render the route.

**Comment by thomas0306** [comment]
With lat/long pairs we can only plot "straight line" between points and sometimes(always) streets were curvy. I think polyline arr would be better which allows our path to stay on the road.

**Comment by KK578** [comment]
I had a peek at the way google-maps API draws the route, and they actually create a point at every point along the curve to ensure the straight lines 'curve' around the road.
So I think the information is already a polyline array.

**Comment by KK578** [comment]
See #4.
