### ISSUE TITLE
Circle glitch

### ISSUE THREAD

**Issue by amankhoza** [KK578/comp3001#30]
If you repeatedly click the my location fab then the user location accuracy circle gets darker and darker until it turns solid blue.

**Comment by KK578** [comment]
I think the map-circle element should contain the geo-location and a google-map-marker inside.
Then it can link the location directly to that element and detect geolocation changes.
On changes, it should unbind the current circle, and rebind it to the marker with the new values.

Access to the current location at a higher level can be grabbed through the map-circle element then, so maybe a rename to location-marker? :P

**Comment by amankhoza** [comment]
The bug lives on, working on it should be fixed soon

**Comment by amankhoza** [comment]
Bug appears to be fixed, but for some reason position seems to be updating very frequently, see "MAP READY" log on console

**Comment by amankhoza** [comment]
I've noticed user location seems to be way more accurate (circle is much smaller) on Chrome compared to firefox

**Comment by amankhoza** [comment]
New type of circle glitch, now circle periodically flashes when user position is updated

**Comment by KK578** [comment]
Merged in #34.
